spring:
  application:
    name: trade-gataway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        id:

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level: debug