spring:
  application:
    name: trade-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idle_trading_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

trade:
  host:
    url:
      mbg: http://localhost:8092