spring:
  application:
    name: common-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        enabled: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

